#!/usr/bin/bash
SPEEDTEST_RESULTS=`speedtest-cli`

DOWN="$(echo $SPEEDTEST_RESULTS | grep -Po "(?<=Download: )\\d*")"
UP="$(echo $SPEEDTEST_RESULTS | grep -Po "(?<=Upload: )\\d*")"

echo "$DOWN/$UP"
